using System;
using System.Collections.Generic;
using System.Text;

namespace Session10Classes
{
    class AutoGeneratedPage : IPage
    {
        public int Id { get; }
        public string Title { get; set; }

        public AutoGeneratedPage()
        {
            Id = new Random().Next(0, 100);
            Title = "Page " + Id;
        }

        public string Render()
        {
            return $"[AutoGenerated]: {Title}";
        }
    }
}
