using System;
using System.Collections.Generic;

namespace Session10Classes
{
    class Program
    {
        static List<Page> _pages = new List<Page>
        {
            new ArticlePage { Id = 0, Title = "Betalningsvillkor" },
            new ArticlePage { Id = 1, Title = "Användarvillkor" },
            new RecipePage { Id = 2, Title = "Ungnsbakt potatis", 
                Recipe = new Recipe
                {
                    Description = "God ungnsbakt potatis",
                    Ingredients = new Ingredient[]
                    {
                        new Ingredient(1, "st", "Bakpotatis"),
                        new Ingredient(10, "g", "Smör"),
                    },
                    Steps = new List<string>
                    {
                        "Förkoka potatisen i vatten",
                        "Tillsätt smör",
                        "Lägg i folie",
                        "Baka i ugn"
                    }
                }
            }
        };

        static void Main(string[] args)
        {
            Ingredient ingredient = new Ingredient(1, "st", "Kycklingfilé á 100g");

            // Ingredient har en metod på instansen
            ingredient.ForPortionsInstance(3);

            // Ingredient har även en metod på klassdefinitionen
            Ingredient.ForPortionsStatic(ingredient, 3);

            // Komma åt statiska egenskaper gör man direkt från klassdefinitionen
            // Ej instansen
            int defaultIngredientAmount = Ingredient.DefaultAmount;

            // Vill man använda sig av innehållet i en statisk egenskap
            //RecipePageTranslations.RecipeHeading;

            foreach (Page page in _pages)
            {
                RenderPageToConsole(page);
            }

            RenderPageToConsole(new AutoGeneratedPage());

            var dateSet = new HashSet<DateTime>();
            var date =  new DateTime(2004, 1, 1);

            //AddToCollection(dateSet, date);
            dateSet.Add(date);
        }

        static void RenderPageToConsole(IPage page)
        {
            if (page is ArticlePage articlePage)
            {
                Console.WriteLine("Found an article page");
            }

            Console.WriteLine(page.Render());
        }

        static void AddToList(List<string> list, string item)
        {
            list.Add(item);
        }

        static void AddToCollection<T>(ICollection<T> collection, T item)
        {
            collection.Add(item);
        }

    }
}
